find_program(CLANG_TIDY_EXE NAMES clang-tidy)
find_program(CPPCHECK_EXE NAMES cppcheck)
find_program(CPPLINT_EXE NAMES cpplint)
find_program(IWYU_EXE NAMES iwyu)

function(add_analizers target)
  if(CLANG_TIDY_EXE)
    # set_target_properties(${target} PROPERTIES CXX_CLANG_TIDY ${CLANG_TIDY_EXE})
  endif()
  if(CPPCHECK_EXE)
    # set_target_properties(${target} PROPERTIES CXX_CPPCHECK ${CPPCHECK_EXE})
  endif()
  if(CPPLINT_EXE)
    # set_target_properties(${target} PROPERTIES CXX_CPPLINT ${CPPLINT_EXE})
  endif()
  if(IWYU_EXE)
    # set_target_properties(${target} PROPERTIES CXX_IWYU ${IWYU_EXE})
  endif()
endfunction(add_analizers target)

